#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

SUFFIX="linearGeometry"
BASE="base"

#Remove case folders
for i in `seq 1 9`;
do
	echo "Removing case files"
	rm -r "${SUFFIX}.$i" 

	echo "Removing results"
	rm -f "${SUFFIX}.displacementErrors.txt"
	rm -f "${SUFFIX}.stressErrors.xx.txt"
	rm -f "${SUFFIX}.stressErrors.xy.txt"
	rm -f "${SUFFIX}.stressErrors.yy.txt"

done
