#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Create the mesh
solids4Foam::runApplication gmsh -3 -format msh2 -algo del2d cube.geo
solids4Foam::runApplication gmshToFoam cube.msh
solids4Foam::runApplication changeDictionary

# Run solver
solids4Foam::runApplication solids4Foam
